apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "{{ .Values.appVersion }}"
            - name: APP_COLOR
              value: "{{ .Values.appColor }}"
            - name: DEPLOYED_BY
              value: "{{ .Values.deployedBy }}"
