FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

ENV APP_VERSION=v1
ENV APP_COLOR=#2c4e50

EXPOSE 5000

CMD ["python", "app.py"]
